# Generated by Django 5.0.7 on 2024-07-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='newslettersubscription',
            old_name='created_at',
            new_name='date_subscribed',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='date_posted',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_image_path/default_image.jpg', upload_to='posts/'),
        ),
    ]
